/// The waveform shape generated by an oscillator.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OscillatorType {
    /// Pure tone, no harmonics.
    Sine,
    /// Odd harmonics only, hollow sound.
    Square,
    /// All harmonics, bright and buzzy.
    Sawtooth,
    /// Odd harmonics, softer than square.
    Triangle,
}
